### ISSUE TITLE
Documentation is broken

### ISSUE THREAD

**Issue by HugoCavalcante** [Coloquinte/Coriolis#1]
It looks like the documentation is broken. The UsersGuide.pdf seems to be automatically generated, but the sources have errors that end up truncating the file. On page 38 it ends abruptly with "system-message ERROR/3 in UsersGuide.rst, line 388 Undefined substituion referenced: 'devtoolset2'". Is anyone still maintaining this software?

**Comment by Coloquinte** [comment]
Hi,
This used to be my working copy of Coriolis, but the project has evolved a lot since then.
It's time I close/redirect this repo. For the up-to-date Coriolis repository, please use https://gitlab.lip6.fr/vlsi-eda/coriolis
